services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smai-backend-api
    command:
      [
        "uvicorn",
        "app.main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8000",
        "--reload",
        "--reload-dir",
        "/app/app",
      ]
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      APP_NAME: SMAI Backend
      APP_VERSION: 0.1.0
      ENVIRONMENT: development
      DEBUG: "true"
    restart: unless-stopped
